stages:
    - pre-merge
    - post-merge
    - release

c-class:
    stage: post-merge
    except:
        - schedules
    script:
        - source /tools/setup.sh
        - python -m configure.main -ispec sample_config/default.yaml
        - make restore
        - make
        - make regress opts='--filter=rv64 --parallel=50 --test_opts='--timeout=120s' --sub' CONFIG_ISA=RV64IMAFDC
        - make regress opts='--filter=rv64 --final'
        - make clean_verif
        - make aapg opts='--config=rv64imafdc* --test_count=10 --parallel=30' CONFIG_ISA=RV64IMAFDC
        - make regress opts='--list=aapg.list --sub --test_opts='--timeout=15m' --parallel=30' CONFIG_ISA=RV64IMAFDC
        - make regress opts='--list=aapg.list --final' CONFIG_ISA=RV64IMAFDC
        - make clean_verif
        - make csmith opts='--test_count=30 --parallel=30' CONFIG_ISA=RV64IMAFDC
        - make regress opts='--list=csmith.list --parallel=30 --sub'  CONFIG_ISA=RV64IMAFDC
        - make regress opts='--list=csmith.list --final'
        - make regress opts="--list=cclass-benchmark-tests.list --sub --test_opts='--nospike --timeout=120s'" CONFIG_ISA=RV64IMAFDC
        - make clean_verif
        - make torture opts='--config=bringup --test_count=1'
        - make torture opts='--config=all --debug' CONFIG_ISA=RV64IMAFDC
        - make regress opts='--list=riscv-torture.list --test_opts='--timeout=30m' --sub' CONFIG_ISA=RV64IMAFDC
        - make regress opts='--list=riscv-torture.list --final'
        - make restore
        - python -m configure.main --clean
    only:
        - master
    tags:
        - core-runner

check-mr-build:
    stage: pre-merge
    except:
        - schedules
    script:
        - source /tools/setup.sh
        - python -m configure.main --clean
        - python -m configure.main -ispec sample_config/default.yaml
        - make
        - make regress opts='--filter=rv64 --parallel=30 --test_opts='--timeout=120s' --sub' CONFIG_ISA=RV64IMAFDC
        - make regress opts='--filter=rv64 --final'
        - make restore
        - python -m configure.main --clean
    only:
        - merge_requests
    when: manual
    tags:
        - core-runner

# checks if the changelog has been updated and the version has also been upgraded
check-mr-compliance:
    stage: pre-merge
    except: 
        - schedules
    script:
        - if [[ $(git diff master -- CHANGELOG.rst) ]]; then echo "CHANGELOG.rst updated"; else\
          echo "Please update CHANGELOG.rst";  exit 1; fi
        - export NEWVER=$(grep -P "^\[.*?\]" CHANGELOG.rst -m1 | awk '{print $1}' | sed 's/[][]//g');
        - export CURVER=$(git describe --tags| cut -f1 -d"-")
        - if [ "$CURRVER" = "$CHNGVER" ]; then  echo "Version of CHANGELOG matches CURRENT VERSION version and needs to be updated"; exit 1;  else  echo "Versions have been updated and ready for push";  fi
        - CURVER=${CURVER//./ }
        - NEWVER=${NEWVER//./ }
        - curpatch=$(echo $CURVER | awk '{print $3}')
        - curminor=$(echo $CURVER | awk '{print $2}')
        - curmajor=$(echo $CURVER | awk '{print $1}')
        - newpatch=$(echo $NEWVER | awk '{print $3}')
        - newminor=$(echo $NEWVER | awk '{print $2}')
        - newmajor=$(echo $NEWVER | awk '{print $1}')
        - if [ $newmajor = $curmajor ]; then\
            if [ $newminor = $curminor ]; then\
              if [ $newpatch -gt $curpatch ]; then echo "Version Check OK";\
              else echo "Please check Patch Version";\
              fi\
            else\
              if [ $newminor -gt $curminor ]; then\
                if [ $newpatch = 0 ]; then echo "Version Check OK";\
                else echo "For Minor changes the patches should be 0";\
                fi\
              else echo "Please check Minor Version";\
              fi\
            fi\
          else\
            if [ $newmajor -gt $curmajor ]; then\
              if [ $newminor = 0 ] && [ $newpatch = 0 ]; then echo "Version Check OK";\
              else echo "For Major changes the minor and patches should be 0";\
              fi\
            else echo "Please check Major Version";\
            fi\
          fi

    only:
        - merge_requests
    tags:
        - core-runner

release:
    stage: release
    script:
        - python3 /scratch/version-extract-rst.py
    only:
        refs:
            - master
    tags:
        - core-runner
    except:
        - schedules
