build64:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - source /tools/setup.sh
        - make restore 
        - make patch
        - make generate_verilog 
        - make link_verilator generate_boot_files
        - make regress opts='--filter=rv64 --parallel=90 --sub'
        - make regress opts='--filter=rv64 --final'
        - make aapg opts="--test_count=30 --parallel=90 --sub"
        - make regress opts='--list=aapg.list --final'
        - make torture opts="--config=all"
        - make regress opts="--list=riscv-torture.list --parallel=40 --sub"
        - make regress opts="--list=riscv-torture.list --final"
    only:
        - master
    tags:
        - c-class-build-regression
