c-class:
    except:
      - schedules
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
      - source /tools/setup.sh
      - cd base-sim/
      - ./manager.sh update_deps
      - make restore
      - make patch
      - make CONFIG=templates/rv64imafdc.inc 
      - make regress opts='--filter=rv64 --parallel=90 --test_opts='--timeout=30s' --sub' CONFIG_ISA=RV64IMAFDC
      - make regress opts='--filter=rv64 --final'
      - make aapg opts='--config=rv64imafdc* --test_count=10 --parallel=30'
      - make regress opts='--list=aapg.list --sub --test_opts='--timeout=15m' --parallel=100' CONFIG_ISA=RV64IMAFDC
      - make regress opts='--list=aapg.list --final' CONFIG_ISA=RV64IMAFDC
      - make csmith opts='--test_count=30 --parallel=100'
      - make regress opts='--list=csmith.list --parallel=100 --sub'  CONFIG_ISA=RV64IMAFDC
      - make regress opts='--list=csmith.list --final'
      - make regress opts="--list=cclass-benchmark-tests.list --sub --test_opts='--nospike --timeout=20s'" CONFIG_ISA=RV64IMAFDC
      - make torture opts='--config=all --parallel=10'
      - make regress opts='--list=riscv-torture.list --test_opts='--timeout=15m' --parallel=20 --sub' CONFIG_ISA=RV64IMAFDC
      - make regress opts='--list=riscv-torture.list --final'
      - make restore
      - make CONFIG=templates/asic_synth.inc release-verilog-artifacts
      - python3 /scratch/version-update.py
      - git pull origin master
      - git describe --tags > ../verilog-artifacts/version.txt
    only:
        - master
    tags:
        - core-runner
    artifacts:
      name: verilog-artifacts
      paths:
        - ./verilog-artifacts

c-class-rv32-nightly:
    only:
      - schedules
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
      - source /tools/setup.sh
      - cd base-sim/
      - ./manager.sh update_deps
      - make patch
      - make restore
      - make CONFIG=templates/rv32imafc.inc
      - make regress opts='--filter=rv32[^!si][^!ud] --test_opts='--timeout=30s' --parallel=90 --sub' CONFIG_ISA=RV32IMAFC
      - make regress opts='--filter=rv32[^!si][^!ud] --final' CONFIG_ISA=RV32IMAFC
      - make regress opts='--filter=rv32si --test_opts='--timeout=30s' --parallel=90 --sub' CONFIG_ISA=RV32IMAFC
      - make regress opts='--filter=rv32si --final' CONFIG_ISA=RV32IMAFC
      - make aapg opts='--config=rv32imafc_bringup --test_count=30 --aapg_opts='--arch=rv32''
      - make regress opts='--list=aapg.list --test_opts='--timeout=3m' --sub --parallel=100' CONFIG_ISA=RV32IMAFC
      - make regress opts='--list=aapg.list --final'
      - make restore clean_verif
      - make CONFIG=templates/rv32imafc_nocache_nobpu.inc
      - make regress opts='--filter=rv32[^!si][^!ud].*p --test_opts='--timeout=30s' --parallel=90 --sub' CONFIG_ISA=RV32IMAFC
      - make regress opts='--filter=rv32[^!si][^!ud].*p --final' CONFIG_ISA=RV32IMAFC
      - make regress opts='--filter=rv32si --test_opts='--timeout=30s' --parallel=90 --sub' CONFIG_ISA=RV32IMAFC
      - make regress opts='--filter=rv32si --final' CONFIG_ISA=RV32IMAFC
      - make aapg opts='--config=rv32imafc_bringup --test_count=30  --aapg_opts='--arch=rv32''
      - make regress opts='--list=aapg.list --test_opts='--timeout=3m' --sub --parallel=100' CONFIG_ISA=RV32IMAFC
      - make regress opts='--list=aapg.list --final'
      - make restore clean_verif
      - make CONFIG=templates/rv32imac.inc
      - make aapg opts='--config=rv32imac_bringup --test_count=30  --aapg_opts='--arch=rv32''
      - make regress opts='--list=aapg.list --test_opts='--timeout=3m' --sub --parallel=100' CONFIG_ISA=RV32IMAC
      - make regress opts='--list=aapg.list --final'
      - make restore clean_verif
    tags:
        - core-runner

c-class-rv64-nightly:
    only:
      - schedules
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
      - source /tools/setup.sh
      - cd base-sim/
      - ./manager.sh update_deps
      - make restore clean_verif 
      - make patch
      - make CONFIG=templates/rv64imafdc.inc
      - make regress opts='--filter=rv64 --parallel=90 --test_opts='--timeout=30s' --sub'
      - make regress opts='--filter=rv64 --final'
      - make aapg opts='--config=rv64imafdc_bringup --test_count=30'
      - make regress opts='--list=aapg.list --test_opts='--timeout=3m' --sub --parallel=100' CONFIG_ISA=RV64IMAFDC
      - make regress opts='--list=aapg.list --final' CONFIG_ISA=RV64IMAFDC
      - make restore clean_verif
      - make CONFIG=templates/rv64imac.inc
      - make aapg opts='--config=rv64imac_bringup --test_count=30'
      - make regress opts='--list=aapg.list --test_opts='--timeout=3m' --sub --parallel=100' CONFIG_ISA=RV64IMAC
      - make regress opts='--list=aapg.list --final'
      - make restore clean_verif
      - make CONFIG=templates/rv64imafdc_nocache_nobpu.inc
      - make regress opts='--filter=rv64 --parallel=90 --test_opts='--timeout=30s' --sub'
      - make regress opts='--filter=rv64 --final'
      - make aapg opts='--config=rv64imafdc_bringup --test_count=30'
      - make regress opts='--list=aapg.list --test_opts='--timeout=3m' --sub --parallel=100' CONFIG_ISA=RV64IMAFDC
      - make regress opts='--list=aapg.list --final' CONFIG_ISA=RV64IMAFDC
      - make restore clean_verif

    tags:
        - core-runner
