build64:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - source /tools/setup.sh
        - make restore 
        - make patch
        - make generate_verilog SYNTH=SIM MUL=fpga ISA=RV64IMAFDC MULSTAGES=8 DIVSTAGES=64 VERBOSITY=0
        - make link_verilator generate_boot_files
        - make regress opts='--filter=rv64[^!si].*p --parallel=90 --sub'
        - make regress opts='--filter=rv64[^!si].*p --final'
        - make aapg opts="--test_count=30 --parallel=90 --sub"
        - make regress opts='--list=aapg.list --final'
        - make torture opts="--config=all"
        - make regress opts="--list=riscv-torture.list --parallel=40 --sub"
        - make regress opts="--list=riscv-torture.list --final"
    only:
        - 23-new-memory-subsystem-integration-with-pipeline
    tags:
        - c-class-build-regression

build32:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - source /tools/setup.sh
        - make restore 
        - make patch
        - make generate_verilog SYNTH=SIM MUL=fpga ISA=RV32IMAFC MULSTAGES=4 DIVSTAGES=32 VERBOSITY=0
        - make link_verilator generate_boot_files
        - make regress opts='--filter=rv32[^!si].*p --parallel=90 --sub'
        - make regress opts='--filter=rv32[^!si].*p --final'
    only:
        - 23-new-memory-subsystem-integration-with-pipeline
    tags:
        - c-class-build-regression
